//
// Generated file, do not edit! Created by opp_msgtool 6.1 from archivoAdquisicion.msg.
//

#ifndef __ARCHIVOADQUISICION_M_H
#define __ARCHIVOADQUISICION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ArchivoAdquisicion;
/**
 * Class generated from <tt>archivoAdquisicion.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet ArchivoAdquisicion
 * {
 * }
 * </pre>
 */
class ArchivoAdquisicion : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const ArchivoAdquisicion& other);

  protected:
    bool operator==(const ArchivoAdquisicion&) = delete;

  public:
    ArchivoAdquisicion(const char *name=nullptr, short kind=0);
    ArchivoAdquisicion(const ArchivoAdquisicion& other);
    virtual ~ArchivoAdquisicion();
    ArchivoAdquisicion& operator=(const ArchivoAdquisicion& other);
    virtual ArchivoAdquisicion *dup() const override {return new ArchivoAdquisicion(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ArchivoAdquisicion& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ArchivoAdquisicion& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ArchivoAdquisicion *fromAnyPtr(any_ptr ptr) { return check_and_cast<ArchivoAdquisicion*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ARCHIVOADQUISICION_M_H

